version: "3.8"

services:
  AGI:
    build: .
    container_name: AGI
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./agi:/agi
    environment:
      - AGI_CONFIG=/agi/config.json
      - AGI_LOG=/agi/log
      - AGI_DATA=/agi/data
      - AGI_PORT=8080
      - AGI_HOST=
      - PINECONE_API_KEY=your-pinecone-api-key
      - PINECONE_ENV=your-pinecone-region
      - OPENAI_API_KEY=your-openai-api-key
      - ELEVENLABS_API_KEY=your-elevenlabs-api-key
      - SMART_LLM_MODEL=gpt-4
      - FAST_LLM_MODEL=gpt-3.5-turbo
      - GOOGLE_API_KEY=
      - CUSTOM_SEARCH_ENGINE_ID=
      - USE_AZURE=False
      - OPENAI_AZURE_API_BASE=your-base-url-for-azure
      - OPENAI_AZURE_API_VERSION=api-version-for-azure
      - OPENAI_AZURE_DEPLOYMENT_ID=deployment-id-for-azure
      - IMAGE_PROVIDER=dalle
      - HUGGINGFACE_API_TOKEN=
      - USE_MAC_OS_TTS=False
      - NAME="AGI"
      - OBJECTIVE="Solve world hunger"
      - INITIAL_TASK="Develop a task list"

  pinecone:
    image: pinecone/pinecone:latest
    container_name: pinecone
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./pinecone:/pinecone
    environment:
      - PINECONE_CONFIG=/pinecone/config.json
      - PINECONE_LOG=/pinecone/log
      - PINECONE_DATA=/pinecone/data
      - PINECONE_PORT=8081
      - PINECONE_HOST=

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/redis
    environment:
      - REDIS_CONFIG=/redis/config.json
      - REDIS_LOG=/redis/log
      - REDIS_DATA=/redis/data
      - REDIS_PORT=6379
      - REDIS_HOST=

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
    volumes:
      - ./rabbitmq:/rabbitmq
    environment:
      - RABBITMQ_CONFIG=/rabbitmq/config.json
      - RABBITMQ_LOG=/rabbitmq/log
      - RABBITMQ_DATA=/rabbitmq/data
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=